---
version: '3.7'
services:
  ## Postgres Docker Compose Config
  postgres-tenpo:
    container_name: postgres-tenpo
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: db-tenpo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork


  ## Sum-Service Docker Compose Config
  sum-service:
    container_name: sum-service
    image: harlem90/sum-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-tenpo:5432/db-tenpo
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - postgres-tenpo
    networks:
      - mynetwork

networks:
  mynetwork: