server:
  port: 8081

spring:
  application:
    name: sum-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db-tenpo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#Resilience4J Properties
resilience4j:
  retry:
    instances:
      percentage:
        max-attempts: 3
        wait-duration: 1s
  ratelimiter:
    instances:
      percentage:
        limit-for-period: 3
        limit-refresh-period: 60s
        limit-type: FIXED
      authentication:
        limit-for-period: 3
        limit-refresh-period: 60s
        limit-type: FIXED

application:
  security:
    jwt:
      secret-key: 4167414E6C323167554C786A776F4C6E7A4D52376842783675427856586D4A57
      expiration: 86400000 # a day
      refresh-token:
          expiration: 604800000 # 7 days


